version: 2.1

jobs:
  build: # name of your job
    machine: # executor type
      image: ubuntu-2004:202010-01
      steps:
        - checkout
        - run:
            name: Install aws-cli  configuring
            command: |
              sudo apt-get install aws-cli -y \
              echo "$AWS_ACCESS_KEY_ID" > .aws/config
              echo "$AWS_SECRET_ACCESS_KEY" >> .aws/config
         - run:
             name: excuting docker image
             command: |
               docker build -t $AWS_ECR_ACCOUNT_URL/genie-ci:latest .
             
             
             
workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
